apiVersion: apps/v1
kind: Deployment
metadata:
  name: dbapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dbapp
  template:
    metadata:
      labels:
        app: dbapp
    spec:
      containers:
        - name: appsrv
          image: ghcr.io/oliver-420/dbapp:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: quarkus-service
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: dbapp
